Develop
hello-robot/stretch_factory pull request #24
Opened 2021-09-26 15:52 UTC by aedsinger

This PR 
* Refactors the code into a stretch_factory library so that utility functions can be used across production software (RDK), RE1 tools, etc
* incorporates a number of improvements to to RE1_firmware_updater (see Gist https://gist.github.com/hello-binit/0bec03e541baff259cbabcdf960c5298). 
** RE1_firmwmare_updater.py now manages installation of the correct version of the arduino-cli

2021-09-26 15:53 UTC, aedsinger commented
RE1_firmware_updater.py now uses the ```supported_protocols``` field of Devices, so newer version of Stretch Body is required that handles dynamic protocols.

2021-09-29 09:53 UTC, hello-binit requested changes
The reduced output is a lot easier to work with. I wasn't able to get the install_path option to work, and I had a few other small issues.

2021-09-29 12:20 UTC, hello-binit commented on python/stretch_factory/firmware_updater.py
> +    def do_update_to_path(self,path_name):
Seems like this affects `--install_branch` too. When the firmware version matches what is currently on-board, it doesn't perform the flash.

```bash
hello-binit@stretch-re1-1002:~$ RE1_firmware_updater.py --arm --install_branch
Collecting information...
.....

################### Select target branch ###################
Collecting information...
....

0: origin/master
1: origin/feature/validate_segments
2: origin/feature/waypoint_trajectories_py3

Please enter desired branch id [0]: 1
Selected branch origin/feature/validate_segments
########################################## UPDATING FIRMWARE TO... ###########################################
HELLO-MOTOR-ARM           | Already at target of Stepper.v0.0.2p1    
System is up to date. No updates to be done
hello-binit@stretch-re1-1002:~$
```

2021-09-29 18:08 UTC, aedsinger commented on python/setup.py
> +    install_requires=['pyserial','pyusb','gitpython']
Done

2021-09-29 18:17 UTC, aedsinger commented on python/stretch_factory/firmware_updater.py
> +                    self.config_info[device]['supported_protocols']=dd.supported_protocols.keys()
Supports the older Stretch Body's now as well

2021-09-29 18:19 UTC, aedsinger commented on python/stretch_factory/firmware_updater.py
> +                print('\n')
Removed

2021-09-29 18:19 UTC, aedsinger commented on python/stretch_factory/firmware_updater.py
> +        print('\n')
Removed

2021-09-29 18:24 UTC, aedsinger commented on python/tools/RE1_firmware_updater.py
> +        u.do_update_to_path(args.install_path)
Done

2021-09-29 19:49 UTC, aedsinger commented on python/stretch_factory/firmware_updater.py
> +    def do_update_to_path(self,path_name):
Fixed relative path handling.

2021-09-29 19:59 UTC, aedsinger commented on python/stretch_factory/firmware_updater.py
> +    def do_update_to_path(self,path_name):
It now 'reinstalls' the firmware if it matches what is currently on-board. For development this is more useful, for users hopefully they'd never do this.

2021-09-29 20:52 UTC, aedsinger commented on python/stretch_factory/firmware_updater.py
> +    def do_update_to_path(self,path_name):
I found that a last minute change I made broke the --install_path code. Working again. Also it now checks if the compile succeeded before proceeding.

2021-09-30 01:13 UTC, hello-binit approved these changes
Ready to merge! Firmware updater tool works reliably well.

2021-09-30 15:41 UTC, merged